### ISSUE TITLE
Предложения по добавлениям

### ISSUE THREAD

**Issue by juwain** [htmlacademy/codeguide#1]
> Хотелось бы видеть соглашение для картинок под ретину, договоренности по иконкам (спрайты раст/svg), семантике кода, связыванию с html c js для работы с dom

**Comment by denisfl** [comment]
А как вы определяете использовать ли современные свойства css или стоит поддерживать старые браузеры?

**Comment by meritt** [comment]
Чаще всего мы работаем с IE11+. Просто иначе невозможно обучать флексбоксу там, где его нет. Ну и наша статистика говорит о том, что нам ничто не мешает использовать IE11+. А дальше уже определяем по наличию хороших полифилов и здравым смыслом.
