### ISSUE TITLE
Доработка JS-кодгайда

### ISSUE THREAD

**Issue by juwain** [htmlacademy/codeguide#15]
Изначальный пулреквест https://github.com/htmlacademy/codeguide/pull/11

**Comment by o0** [comment]
Комментарии @zeckson по MD:
> строки более 80 символов длиной, снижают скорость чтения заставляя читатаеля

- [ ] Пруф или не было!

---
- [ ] Если хотя бы одна из переменных что? Аааааа!!! Интрига!

---
> Аргументы функций и вызовы через цепчку отделяются четырьмя пробелами

- [ ] У нас в eslint двумя. Настало время определиться:

---
> Альтернативный способ переносить аргументы — выравнивать их с открывающей скобкой

- [ ] Автореформаттеры ломают такой способ

---
> последняя и после сортировки и удаления нужно перепроверить получившийся список на валидность.

- [ ] это про что?

> @o0: я когда писал так ощущал, а теперь не думаю вообще, что перенос точки проблема. Даже грешным делом начал подумывать удалить и разрешить все это безобразие. Как ты думаешь?

---
> В каждом файле нужно использовать директиву `'use strict'`

- [ ] Уточнить — для ES без модулей

---
> Положительный побочный эффект такого стиля заключается в том,

- [ ] Мне кажется это лишнее для стайлгайда. Это же не методическое пособие.

---
> Замыкания

- [ ] Это чё?

**Comment by kaineer** [comment]
### Замечания

> Запрещено использовать запятую в конце списков, объектов или наоборов параметров функции

- [x] Опечатка, «наоборов», а должно быть «наоборот»

> В однострочных объектах и при деструктуризации фигурные скобки отбиваются пробелами с двух сторон

- [x] Тяжело воспринимать без примера

> В объектах после объявления ключа не ставится пробел. После двоеточия, которое отделяет в объектах ключ от значения

- [x] Тяжело воспринимать без примера

> При объявлении анонимных функций, скобки с параметрами отделаются пробелом

- [x] «отделяются», опечатка

> При создании генераторов, звездочка идет сразу

- [x] «идёт», Ё.

> Оператор вызова функции () не отделяется круглыми скобками от названия функции

- [x] Наверное, всё-таки, пробелами?

> `if (myValue === 1) {}`

- [x] Стоит добавить многоточие внутрь блока, наверное.

> `var do = function() {`

- [x] В качестве имени переменной использовано ключевое слово

> Операторы

- [ ] Ещё примеров, пожалуйста.

> Переменные объявляются через var только при наличии проблем с поддержкой кода

- [x] «с поддержкой ES6»?

> Для каждой переменной используется отдельный var, let или const

> Запрещено переносить запятую на новую строку при создании множественных переменных через один var

- [x] Тут надо или крест снять или уже одеться, а то как-то сами себе противоречим.

> После двоеточий и точек с запятым ставятся пробелы.

- [x] «точек с запятыми», опечатка.

> В коде нет выражений, значения которых не записываются в переменные, параметры функций, свойства объектов и не передаются как параметры функций

- [x] Такое ощущение, что до первой запятой текст идёт связно, а потом: ХРЯСЬ! - и куска текста нет, продолжается не связанное с началом предложение. А всё из-за того, что предлог «в» несколько раз опущен.

> Лейблы используются с конструкциями break и continue для направленного выхода из икла и могут привести к слишком сложному для понимания коду

- [x] «из икла». Заменить на «из цикла»

### Вопросы

> В числах запрещено опускать ноль в дробной и целой части

- [x] А как можно опустить ноль в дробной части?
