### ISSUE TITLE
[.htmlhintrc]Правило id-class-value

### ISSUE THREAD

**Issue by SlavaMilin** [htmlacademy/codeguide#31]
>Студент использовал codestyle Академии .htmlhintrc  https://github.com/htmlacademy/codeguide/blob/master/.htmlhintrc . И VS Code ругается на правило “id-class-value”: “dash”, хотя классы указываются верно.

![image](https://user-images.githubusercontent.com/20872744/55729391-b729cf00-5a1e-11e9-90aa-9da5c47f7455.png)

**Comment by nikolai-shabalin** [comment]
Пофиксили, но уже в другом репозитории - https://github.com/htmlacademy/htmlhint-config-htmlacademy
