### ISSUE TITLE
attr-lowercase

### ISSUE THREAD

**Issue by efiand** [htmlacademy/codeguide#32]
Добрый день. Извините за беспокойство, есть предложение изменить `.htmlhintrc`:

```json
  "attr-lowercase": true,
```
на
```json
  "attr-lowercase": ["viewBox", "preserveAspectRatio"],
```

**Comment by nikolai-shabalin** [comment]
Кажется SVG конкретно так подсечку делает для этого правила:
* systemLanguage
* surfaceScale
* externalResourcesRequired
* viewTarget

но это всё какие-то очень специфичные и редкие атрибуты.

Ваш пример добавил, так как он часто встречаемый. Будем по мере поступления проблем обновлять правилою.

Спасибо за предложение! =)

**Comment by efiand** [comment]
Николай, благодарю! Да, прислал именно то, с чем встречался, в том числе и при верстке учебных проектов Академии.

**Comment by nikolai-shabalin** [comment]
HTMLHint переехал в другой репозиторий - https://github.com/htmlacademy/htmlhint-config-htmlacademy, а также обновился до последней версии и получил новые правила.

**Comment by efiand** [comment]
Спасибо! И `"id-class-value": false` - тоже хорошо, иначе с БЭМ были проблемы.
