### ISSUE TITLE
[html-css] Синтаксис - Опечатка

### ISSUE THREAD

**Issue by sukhikh18** [htmlacademy/codeguide#35]
http://codeguide.academy/html-css.html
Необязательные закрывающие теги (например, </li> или </body>) не пропускаются.

**Comment by nikolai-shabalin** [comment]
А в чём опечатка заключается? Что-то понять не могу

**Comment by sukhikh18** [comment]
Не помню уже.. возможно тегов `</li>`,  `</body>` не было раз такую цитату вставил.
