### ISSUE TITLE
Почему 6 символов вместо 3 при указании цвета?

### ISSUE THREAD

**Issue by ademaro** [htmlacademy/codeguide#4]
До сих пор не понимаю, в чём смысл писать 6 символов вместо 3 при указании цвета в стилях... 

При использовании трёх же мы быстрее можем воспринять сколько там символов: `#fff` вместо `#ffffff`, читаемость на лицо. Студентов, выпускающихся из академии много и почему бы им не прививать более читаемый и распространённый вариант использования.

**Comment by ademaro** [comment]
Вообще зачем что-то велосипедить, если есть всё: http://instanceof.pro/code-guide/ 

Или не устраивает чем-то?)

**Comment by juwain** [comment]
Привет. Почему так — в небольшой статье https://htmlacademy.ru/blog/62.

**Comment by ademaro** [comment]
Про сокращения очень не согласен, это вопрос читаемости как раз, постарался описать выше свой комментарий. Все лидеры отрасли как раз говорят о сокращённой версии. Но ваша позиция ясна, ваше право, убрал ссылку на вас, пришлось поставить оригинал)

**Comment by meritt** [comment]
Вам просто показалось, что у нас перевод чьего-то гайда. Но это не так. Мы использовали в качестве референсов многие известные гайды и собрали свой собственный, который отвечал бы нашему пониманию процесса обучения. Каждое изменение нами очень прочувствованно и абсолютно осознанно.
