### ISSUE TITLE
Может привести к единому виду последовательность title и кодировки?

### ISSUE THREAD

**Issue by tsergeytovarov** [htmlacademy/codeguide#5]
Тут кодировка снизу
![2015-10-20 18 29 29](https://cloud.githubusercontent.com/assets/3905611/10612234/9919b27a-7758-11e5-8642-453f5ad799c0.png)
Тут кодировка сверху
![2015-10-20 18 29 34](https://cloud.githubusercontent.com/assets/3905611/10612235/9932ab36-7758-11e5-8816-9198c2ea1187.png)

**Comment by meritt** [comment]
PR welcome.

**Comment by meritt** [comment]
Закрыли в #6
